import Head from 'next/head';
import Image from 'next/image';
import LinksCard from '../components/LinksCard';

export default function Home() {
  const data = [
    {
      image: '/images/aldogithub.jpeg',
      name: 'Aldo',
      socials: {
        twitter: 'https://twitter.com/aldocasareto',
        facebook: 'https://facebook.com',
        instagram: 'https://instagram.com',
      },
      work: {
        ivy: 'https://ivyoak.com',
        voteRookie: 'https://voterookie.com',
        ekomi: 'https://ekomi.com',
      },
    },
  ];

  return (
    <>
      <Head>
        <title>Link Tree</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex items-center justify-center mt-28 flex-col px-40 space-y-4'>
        <Image
          src={data[0].image}
          alt={data[0].name}
          width={200}
          height={200}
          className='rounded-full'
        />
        <LinksCard data={data} />
      </div>
    </>
  );
}
