import Head from 'next/head';

import UserCard from '../components/LinkCard.tsx';

export default function Home() {
  return (
    <>
      <Head>
        <title>Link Tree</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex items-center justify-center mt-28 flex-col px-40 space-y-4'>
        <UserCard />
      </div>
    </>
  );
}
